### ISSUE TITLE
cmp_version is unable to correctly sort rpm with uneven release parts

### ISSUE THREAD

**Issue by rbikar** [release-engineering/ubi-population-tool#104]
*Description:*
There is an issue with comparison of rpm version in cmp_version module.
For details see https://github.com/kata198/cmp_version/issues/1 

*Note:*
I created PR https://github.com/kata198/cmp_version/pull/2  that should fix this issue
but maintainer of that repo hasn't responded yet. 
Until upstream cmp_version is released with fix,  would it be ok to incorporate source code of cmp_version to ubipop code? Or can you think of any better solution? 
@danrodrig   @rohanpm  @JayZ12138

**Comment by rohanpm** [comment]
I guess that we should in fact either define our own comparison method (which seems OK to be initialized from existing cmp_version), or find another correct library.

Looking at cmp_version, I'm not sure it was ever really suitable for our purpose.  The description says:

> A script and python module to compare version numbers. Use this to compare the version strings of packages, modules, really anything.

There's a specific algorithm for comparing versions of *rpms*.  The author of this library does use RPMs as an example but it's never clearly stated that this is a library for "rpm version comparison".

The README also says:

> Since version 3.0, cmp_version supports all kinds of complex version numbers

But this can't be true, there's unlimited possible version schemes.  The concept of a library being able to compare "any" versions when only provided with two strings doesn't seem to make sense, as there can be conflicting version schemes.

So I would be in favor of dropping cmp_version dependency and replacing it with something which is explicitly for RPMs (is https://github.com/sassoftware/python-rpm-vercmp workable?) or just shipping our own implementation of vercmp.

**Comment by rbikar** [comment]
I early version we used python-rpm-vercmp, it also failed comparing in some cases (I think it wrongly compared some parts of release).
I think that implementing our own method for this purpose may be to best solution also in terms of maintainability.
