### ISSUE TITLE
keep_n_latest_packages() may add duplicated packages to output set

### ISSUE THREAD

**Issue by rbikar** [release-engineering/ubi-population-tool#105]
**Description:**
keep_n_latest_packages()  method can add duplicates to output set of rpms in case they matched  by whitelist and also when the same package comes from module's artifacts.
This should be avoided so we don't have duplicated associations.

What most probably happens is that there are two packages with the same name and filename but is_modular attr. differs. Current implementation will add both of those pkgs to output set and they are both associated.
**Acceptance criteria:**
* Output sets of binary and debug rpms should contain only unique rpms
* There is no duplicated associated of binary and debug rpms

**Note:**
* There is also issue  #52 that was partially fixed but we still have duplicated associations for source rpms but the reason is not only is_modular attr. but there are also multilib pkgs that the same sourcerpm (x.x86_64.rpm and x.i686.rpm have the same SRPM)

**Comment by danrodrig** [comment]
The case where input package list contains duplicated modular packages was not covered in #123
