### ISSUE TITLE
log_curent_content should nofity that there is nothing in the repo

### ISSUE THREAD

**Issue by alexandrevicenzi** [release-engineering/ubi-population-tool#12]
These messages are a bit awful if there's no content in the repo:

```
[INFO    ] Current modules in repo: ubi-7-server-rpms__7_DOT_6__x86_64
[INFO    ] Current rpms in repo: ubi-7-server-rpms__7_DOT_6__x86_64
[INFO    ] Current srpms in repo: ubi-7-server-source-rpms__7_DOT_6__x86_64
```

If there's no content the message should be something else, probably:

`[INFO    ] No modules in repo: ubi-7-server-rpms__7_DOT_6__x86_64`

**Comment by rbikar** [comment]
This issue is not resolved and is still valid for logging of current content in repos.

**Comment by rbikar** [comment]
Issue closed in internal backlog with no intentions of fixing.
