### ISSUE TITLE
Tests broken for Python 2.7 and 3.5

### ISSUE THREAD

**Issue by nathanegillett** [release-engineering/ubi-population-tool#134]
#### Summary
Several tests are suddenly failing for Python 2.7 and Python 3.5.
https://travis-ci.org/release-engineering/ubi-population-tool/builds/588606914?utm_source=github_status&utm_medium=notification

#### Issue Type
- Bug Report

#### Steps to reproduce
Run CI suite by creating a pull request.
Tested here: #133 

#### Actual results
Tests all seem to fail with the following;
E           ValueError: No JSON object could be decoded
/opt/python/2.7.15/lib/python2.7/json/decoder.py:382: ValueError
------------------------------ Captured log call -------------------------------
WARNING  urllib3.connectionpool:connectionpool.py:298 Connection pool is full, discarding connection: foo.pulp.com

#### Expected results
Tests should all pass successfully.

#### OS / Environment
Travis CI

#### Additional Information
Failing tests:
tests/test_pulp.py::test_retries[True-500-None-search_repo_by_cs-retry_args0-{}-10] FAILED
tests/test_pulp.py::test_retries[True-500-None-search_repo_by_id-retry_args1-{}-10] FAILED
tests/test_pulp.py::test_retries[True-500-None-search_rpms-retry_args2-[]-10] FAILED
tests/test_pulp.py::test_retries[True-500-None-search_modules-retry_args3-[]-10] FAILED
tests/test_pulp.py::test_retries[True-500-None-wait_for_tasks-retry_args4-{"state":"finished","task_id":"fake-tid"}-10] FAILED
tests/test_pulp.py::test_retries[True-500-None-search_tasks-retry_args5-[]-10] FAILED
tests/test_pulp.py::test_retries[True-500-None-unassociate_units-retry_args6-{"spawned_tasks":[]}-10] FAILED
tests/test_pulp.py::test_retries[True-500-None-associate_units-retry_args7-{"spawned_tasks":[]}-10] FAILED
tests/test_pulp.py::test_retries[True-500-None-publish_repo-retry_args8-{"spawned_tasks":[]}-10] FAILED
tests/test_pulp.py::test_retries[True-500-3-search_repo_by_cs-retry_args9-{}-3] FAILED

**Comment by danrodrig** [comment]
The failing test are due to urllib3>1.25.3.

**Comment by nathanegillett** [comment]
Thanks for investigating that, @danrodrig

**Comment by danrodrig** [comment]
We tried changing the requirements in on PR, but, as @rbikar pointed out:

> Requiring version of urllib<=1.25.3 created some conflict with vesrion that uses travis (cov_travis TOX_ENV)

`raise VersionConflict(dist, req).with_context(dependent_req) pip._vendor.pkg_resources.ContextualVersionConflict: (urllib3 1.25.6 (/home/travis/build/release-engineering/ubi-population-tool/.tox/cov-travis/lib/python3.5/site-packages), Requirement.parse('urllib3<=1.25.3'), {'ubi-population-tool'})`
