### ISSUE TITLE
Don't use rpmUtils

### ISSUE THREAD

**Issue by rohanpm** [release-engineering/ubi-population-tool#5]
ubipop module currently has some imports from rpmUtils:

```
ubipop/__init__.py:from rpmUtils.miscutils import splitFilename, compareVerOnly
```

It would be better to avoid depending on that.  The reason is that rpmUtils comes from yum 3, and:

- yum 3 is already on the verge of being deprecated, e.g. in Fedora 31 it will be removed https://fedoraproject.org/wiki/Changes/Retire_YUM_3?rd=Changes/Deprecate_YUM_3 , in RHEL8 it also will be absent.
- the replacement, dnf, doesn't provide this API
- yum/rpmUtils isn't installable from PyPI, which complicates development and CI

Let's remove the code depending on rpmUtils and replace it with something else installable from PyPI.

**Comment by rbikar** [comment]
Yeah, 
actually I have already changed this.
For compareVerOnly I found replacement in PyPI: rpm_vercmp. Now added in _pulp.py to Package class.
I couldn't find anything in PyPI for splitFilename, I borrowed that code, now can be seen in _utils.py.

**Comment by rohanpm** [comment]
Oops, I was looking at old remote when I filed this.
