### ISSUE TITLE
Check output of associate and unassociate tasks and log result 

### ISSUE THREAD

**Issue by rbikar** [release-engineering/ubi-population-tool#51]
At the moment ubipop doesn't support check of tasks spawned by associate and unassociate tasks.
We should check result of each task and log result (ok, no action, errors) with corresponding task_id.

**Comment by alexandrevicenzi** [comment]
Relates to #18 as well.

**Comment by rohanpm** [comment]
- If these tasks fail, should overall process fail?  I'm thinking it should.
- Should the checking include looking at units_successful, to check that what was associated matches what we expected to be associated?  Less sure about this, I'm thinking it's OK to leave that out though, unless we find specific problems which would be solved by that.

**Comment by rbikar** [comment]
@rohanpm 
If these tasks fail, process for current repo set (binary, debug, source) should stop and continue with another one.
The second thing, I am not sure here as well...but it might fix #27 ... which should result in warning that package is not available in input repo. Also there are other (maybe better) means how to fix #27.

**Comment by rbikar** [comment]
This issue is not needed because of planned refactoring (move to pubtools-pulplib).
