### ISSUE TITLE
Failing tests on Python 3.7

### ISSUE THREAD

**Issue by alexandrevicenzi** [release-engineering/ubi-population-tool#82]
Test case `tests/test_pulp.py::test_retries` introduced by #53 is failing on Python 3.7.

Tests should work on both 2.x and 3.x.

There's a deprecation warning on tests about this.

```
tests/test_pulp.py::test_retries
  /home/travis/build/release-engineering/ubi-population-tool/.tox/cov-travis/lib/python3.5/site-packages/requests/models.py:750: PendingDeprecationWarning: generator 'HTTPResponse.stream' raised StopIteration
    for chunk in self.raw.stream(chunk_size, decode_content=True):
```

**Comment by alexandrevicenzi** [comment]
PR #86 include Python 3.5 on CI.

I noticed that the code only fails on Python 3.7 because I was running on my Fedora. On 3.5 it works.

**Comment by rbikar** [comment]
`tests/test_pulp.py` was removed in #223 

Closing
