### ISSUE TITLE
How to deal with modular packages not included in modulemd artifacts?

### ISSUE THREAD

**Issue by JayZ12138** [release-engineering/ubi-population-tool#89]
There's such a piece of code in keep_n_latest_packages:

    packages_to_keep = []
    non_modular_pkgs = []
        for package in packages:
            if package.is_modular:
                for module_name_stream, packages_ref_by_module in \
                        self.repos.pkgs_from_modules.items():
                    pkgs_filenames_from_modules = [pkg.filename for pkg in packages_ref_by_module]
                    if package.filename in pkgs_filenames_from_modules \
                            and module_name_stream in self.repos.modules:
                        # this skips modular pkgs that are not referenced by module
                        packages_to_keep.append(package)
            else:
                non_modular_pkgs.append(package)

The logic here looks flawed: if the package is modular and it's not listed in packages_ref_by_module, it's thrown away silently, not going to non_modular_pkgs or packages_to_keep either. Is this the right behavior we expected?

**Comment by JayZ12138** [comment]
feel free to close it if this is the right behavior we want @rbikar

**Comment by rbikar** [comment]
@JayZ12138 
I believe that current behavior is ok.
In order to keep modular rpm in output repo it has to be referenced by some module.
As we discussed elsewhere, we should not probably rely 100% on is_modular field from pulp.
