### ISSUE TITLE
Hide API for now

### ISSUE THREAD

**Issue by rohanpm** [release-engineering/ubi-population-tool#9]
The concept of this project is:

- have a CLI which can be used for UBI repo population directly
- have an API which can be used to integrate UBI repo population into other tools

Looking at the API, I think there's a fair few problems with it that really ought to be fixed before we could claim the API is stable:

- relationship between UbiPopulate and UbiPopulateRunner is unclear, are callers allowed to create instances of either or is one of them just an implementation detail?
- methods which are probably critical like populate_ubi_repos have no explanation of what they do
- There's methods with public-looking names which probably shouldn't be public, and also spelling errors in method names, e.g. log_curent_content
- There's methods which seem to be intended as public API based on their name and the fact they have docstrings, but probably can't be used due to the fact that they accept arguments of non-public type.  For example get_packages_names_by_profiles has a doc string and name implying it's supposed to be public API, but one of the arguments is a list of Module objects from private module '_pulp'; how is the caller supposed to get instances of that?
- The API doesn't provide public methods which can be used for the original concept put forward for this library: calculate *what should be done* on Pulp, without actually doing it, so that the tool performing actions on Pulp can integrate with its own logic for triggering Pulp tasks, publishing repos etc.

It seems like it would take a fair amount of additional work to get these problems sorted out.

We've got a few options of what to do here:

1. Try to revise API to fix all current problems before putting this into production
2. Or just publish API as it is and hope to improve it later
3. Or keep the whole API private for now and revisit later

To meet our current goals, the only thing we really need right now is the working CLI.  The true requirement for a proper API only comes in later when we want to integrate this with existing tools.  Therefore I'm thinking maybe we should do (3), postpone having *any* supported API and return to it when we're ready to finish it properly.

What do you think?  If you agree with that, then I think in practice the way I'd suggest how to do this is:

- adjust project docs to advertise this as just a CLI tool, don't mention library/API at all
- keep version number < 1.0.0 for now.  Reserve 1.0.0 for the first version where we have an API we can support long-term.

**Comment by rbikar** [comment]
For now I would go with option 3.
For future I expect that only UbiPopulate will be public.
