### ISSUE TITLE
Skip populating _DOT_ repos with equal or older than current release version

### ISSUE THREAD

**Issue by JayZ12138** [release-engineering/ubi-population-tool#92]
Currently, the UBI population does various work on DOT repos, such as 

> 2019-05-07 18:54:42 +0000 [INFO    ] Publishing ubi-7-server-rpms__7_DOT_1__x86_64 in yum_distributor
> 2019-05-07 18:54:42 +0000 [INFO    ] Publishing ubi-7-server-debug-rpms__7_DOT_1__x86_64 in yum_distributor
> 2019-05-07 18:54:42 +0000 [INFO    ] Publishing ubi-7-server-source-rpms__7_DOT_1__x86_64 in yum_distributor
> 2019-05-07 18:57:40 +0000 [INFO    ] Publishing ubi-7-server-rpms__7_DOT_0__x86_64 in yum_distributor
> 2019-05-07 18:57:40 +0000 [INFO    ] Publishing ubi-7-server-debug-rpms__7_DOT_0__x86_64 in yum_distributor
> 2019-05-07 18:57:40 +0000 [INFO    ] Publishing ubi-7-server-source-rpms__7_DOT_0__x86_64 in yum_distributor

However, we are not publishing the older versions to the public and the only point of the DOT repos for UBI is to make it possible to prepare pre-release content. The UBI population should skip these older repos.

**Comment by rohanpm** [comment]
I'm not sure whether ubi-population-tool currently has access to the needed info to achieve this.

If it doesn't, we may first need to figure out a way to expose necessary info on Pulp repos, e.g. by modifying cdn-utils to write needed info into repo notes.

**Comment by rbikar** [comment]
I think needed information must be added to repo notes. I believe there is no way how to find **current release version** just by comparing some repo notes that are currently available in related repos.

**Comment by nathanegillett** [comment]
Further addressed by #130
