### ISSUE TITLE
Do not trust 'is_modular' field

### ISSUE THREAD

**Issue by rbikar** [release-engineering/ubi-population-tool#94]
**Description:**
Currently we trust **is_modular** field in rpm units. But this field is not really reliable.
It can only be trusted, if the value is True. 
If it's False it can be modular and also non-modular.

We should implement check for this field:
E.g. maybe something like: take rpm, check it's existence in any modulemd associated to repo and act accordingly. 

*Acceptance criteria:*
- Do not use value of **is_modular** field from pulp
- When adding rpms to output set from modules artifacts, set always is_modular to True
- When adding rpms to output set from binary rpm repo, do search for that rpm in associated modulemd units in input repo and set *is_modular* accordingly.

**Comment by danrodrig** [comment]
@rbikar I just found this, https://github.com/pulp/pulp_rpm/pull/1368 https://pulp.plan.io/issues/4869
