### ISSUE TITLE
AssertionError: "httpd" not in the repository.

### ISSUE THREAD

**Issue by alexandrevicenzi** [release-engineering/ubi-population-tool#98]
If we run the integration test on Fedora 28 it fails with:

`AssertionError: "httpd" not in the repository.`

This is because yum from F28 returns a slight different output from F29 yum.

**Comment by alexandrevicenzi** [comment]
The function that fails is `query_repo_rpms` and I'm not really sure if the problem is the yum or if the repo is missing some required file to work with older yum version.

**Comment by danrodrig** [comment]
I ran into this issues today and I can confirm that the httpd package is missing in the httpd module for the input repo. More info in downstream tracking as the CI runs internally.
